version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: fumbrel-app
      APP_PORT: 3000
  server:
    image: ghcr.io/willitmod/fumbrel:0.1.0-dev@sha256:a2f6f66a6227264ff88bd2053b36ea09ea55193b01730d467dfefd005165968b
    hostname: fumbrel-app
    restart: on-failure
    init: true
    user: "1000:1000"
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=32m,uid=1000,gid=1000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FUMBREL_APP_PATH: "${APP_DATA_DIR}"
    volumes:
      - /etc/ssh/ssh_host_ed25519_key.pub:/host/ssh_host_ed25519_key.pub:ro
